### ISSUE TITLE
numpy.linalg.LinAlgError: Eigenvalues did not converge

### ISSUE THREAD

**Issue by Arong-gong** [csliuwei/CrossCultureCode#1]
刘博士，你好  :-)
我代码跑了一半，出现了这个错误，调了很久不知道是什么原因，如果你有时间的话，还望指导一下，感谢
Traceback (most recent call last):
  File "main.py", line 118, in <module>
    predict_out, cca_loss, output1, output2, partial_h1, partial_h2, fused_tensor, alpha  = mymodel(train_eeg_used, train_eye_used)
  File "xxx/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "xxx/dataset/SEED-V/src/src/DCCA-with-attention-mechanism/utils.py", line 306, in forward
    cca_loss, partial_h1, partial_h2 = cca_metric_derivative(output1.detach().cpu().numpy(), output2.detach().cpu().numpy())
  File "xxx/dataset/SEED-V/src/src/DCCA-with-attention-mechanism/utils.py", line 145, in cca_metric_derivative
    [D1, V1] = np.linalg.eigh(SigmaHat11)
  File "<__array_function__ internals>", line 5, in eigh
  File "xxx/anaconda3/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 1446, in eigh
    w, vt = gufunc(a, signature=signature, extobj=extobj)
  File "xxx/anaconda3/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 103, in _raise_linalgerror_eigenvalues_nonconvergence
    raise LinAlgError("Eigenvalues did not converge")
numpy.linalg.LinAlgError: Eigenvalues did not converge

**Comment by csliuwei** [comment]
这个我也遇到过，我当时猜测是和原始数据以及中间计算结果有关，最后是重复跑了几次跑完的。报错的是矩阵分解过程出错，因为是调用库的内部实现，我没有深入看每一步的计算结果。我建议首先多跑几次，如果每一次都有问题，可以尝试把计算矩阵时候的常数加大点。

**Comment by Arong-gong** [comment]
感谢刘博士的回复，答疑解惑！

**Comment by 384068026** [comment]
> 刘博士，你好 :-) 我代码跑了一半，出现了这个错误，调了很久不知道是什么原因，如果你有时间的话，还望指导一下，感谢 Traceback (most recent call last): File "main.py", line 118, in predict_out, cca_loss, output1, output2, partial_h1, partial_h2, fused_tensor, alpha = mymodel(train_eeg_used, train_eye_used) File "xxx/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl result = self.forward(*input, **kwargs) File "xxx/dataset/SEED-V/src/src/DCCA-with-attention-mechanism/utils.py", line 306, in forward cca_loss, partial_h1, partial_h2 = cca_metric_derivative(output1.detach().cpu().numpy(), output2.detach().cpu().numpy()) File "xxx/dataset/SEED-V/src/src/DCCA-with-attention-mechanism/utils.py", line 145, in cca_metric_derivative [D1, V1] = np.linalg.eigh(SigmaHat11) File "<**array_function** internals>", line 5, in eigh File "xxx/anaconda3/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 1446, in eigh w, vt = gufunc(a, signature=signature, extobj=extobj) File "xxx/anaconda3/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 103, in _raise_linalgerror_eigenvalues_nonconvergence raise LinAlgError("Eigenvalues did not converge") numpy.linalg.LinAlgError: Eigenvalues did not converge



> 刘博士，你好 :-) 我代号跑了一半，出现了这个错误，调了很久不知道是什么原因，如果你有时间的话，还望指点一下，谢谢 Traceback (most recent call last ) main.py", line 118, in predict_out, cca_loss, output1, output2, partial_h1, partial_h2, fused_tensor, alpha = mymodel(train_eeg_used, train_eye_used) 文件 "xxx/python3.8/site-packages/torch/nn/modules/module .py”，第 722 行，在 _call_impl result = self.forward(*input, **kwargs) 文件“xxx/dataset/SEED-V/src/src/DCCA-with-attention-mechanism/utils.py”中，行306、正向 cca_loss, partial_h1, partial_h2 = cca_metric_derivative(output1.detach().cpu().numpy(), output2.detach().cpu().numpy()) 文件“xxx/dataset/SEED-V/ src/src/DCCA-with-attention-mechanism/utils.py”，第 145 行，在 cca_metric_derivative 中 [D1, V1] = np.linalg.eigh(SigmaHat11) 文件“< **array_function** internals>”，第 5 行，在 eigh 文件“xxx/anaconda3/lib/python3.8/site-packages/numpy/linalg/linalg.py ”，第 1446 行，在 eigh w，vt = gufunc(a, signature=signature, extobj=extobj) 文件“xxx/anaconda3/lib/python3.8/site-packages/numpy/linalg/linalg.py”，第 103 行, 在 _raise_linalgerror_eigenvalues_nonconvergence raise LinAlgError("Eigenvalues did not converge") numpy.linalg.LinAlgError: Eigenvalues did not converge

您好，能留个联系方式吗？
我有一些问题想向您请教
非常感谢！

**Comment by csliuwei** [comment]
不好意思，回复得晚了。

啊 这个问题我也遇到过，不过我看到是矩阵求解的问题就没有深究。
最后我好像是通过记录程序进度，然后重新跑解决的。我记得这个适合数据有关的，可能是batch的大小，也可能是其他的。
我最后是重新跑了几遍，这个问题我没有很好地处理好。

我的邮箱： liuwei.cpp AT gmail.com

有问题可以给我发邮件，我尽量回答。
